#pragma once

#define SCREEN_WIDTH 650
#define SCREEN_HEIGHT 438

#define MAP_HEIGHT 13
#define MAP_WIDTH 16

#define TILE_WIDTH 32
#define TILE_HEIGHT 32

#define SCREENSHAKE_DURATION 0.25f

const float JUMP_FORCE_DECREMENT = 1200.0f;
const float INITIAL_JUMP_FORCE = 930.0f; 
const float INITIAL_JUMP_FORCE_SMALL = 400.0f;